name: My first job

on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest

    environment:
      name: this
      url: https://github.com/ka9an/denopendabot

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_PUBLIC_BUCKET: ${{ secrets.R2_PUBLIC_BUCKET }}
      PRODUCTION_BRANCH: main

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn 

      - name: Setup
        run: yarn setup:production
      - name: Deploy to Cloudflare Pages
        run: yarn deploy:github

